apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name}}-{{ randAlphaNum 5 | lower }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{.Release.Name}}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name:  migrate
        image: {{ .Values.stf.image.repository }}:{{ .Values.stf.image.tag }}
        imagePullPolicy: {{ .Values.stf.image.pullPolicy }}
        command: ["stf"]
        args: ["migrate"]
        env:
        - name: RETHINKDB_PORT_28015_TCP
          value: "tcp://{{.Values.db.url}}:{{.Values.db.port}}"
        - name: RETHINKDB_ENV_AUTHKEY
          value: "{{.Values.db.password}}"
        resources:
{{ toYaml .Values.stf.migration.resources | indent 10 }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
